name: smart_list
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  charts_flutter: ^0.11.0
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  expansion_tile_card: ^2.0.0
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_database: ^9.0.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6
  http: ^0.13.4
  intl: ^0.17.0
  line_icons: ^2.0.1
  lottie: ^1.3.0
  path: null
  syncfusion_flutter_charts: ^20.1.60+1
  url_launcher: ^6.1.3
  toast: ^0.2.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_products.gif
    - assets/images/no_products1.gif
    - assets/images/bg.jpg
    - assets/images/bg1.jpg
    - assets/images/bg2.jpg
    - assets/images/team.png
    - assets/images/linkedin.png
    - assets/images/abstract_nn.jpg
    - assets/images/login_bg.jpg
    - assets/logos/google_logo.png
    - assets/logos/facebook_logo.png
    - assets/logos/smart_list_logo.png

    - assets/lottie/empty-cart.json
